name: Jonathan Warner
markdown: kramdown
timezone: Australia/Melbourne
future: false
lsi: true
gems:
  - jekyll-sitemap
  - jekyll-feed

# Permalinks
permalink: pretty

# Page info etc
title: Jonathan Warner
tagline: 'Generic developer profile?'
#description: A place to showcase what I'm working on
url: toadhats.github.io
baseurl: /

author:
  name: Jonathan Warner
  url: https://github.com/toadhats
  email: limule@icloud.com
  avatar: /images/portrait.jpg


# Custom variables
version: 0.1
github:
  repo: https://github.com/toadhats/toadhats.github.io
  page: https://github.com/toadhats
