name: Jonathan Warner
markdown: kramdown
timezone: Australia/Melbourne
future: false
lsi: true
gems:
  - jekyll-sitemap

# Custom variables
version: 0.1
github:
    repo: https://github.com/toadhats/toadhats.github.io
    page: https://github.com/toadhats
